<template><Teleport to="body"><div v-if="open" class="tour-layer" role="dialog" aria-modal="true" :aria-label="t('tour.title')"><button class="tour-scrim" :aria-label="t('common.close')" @click="close"/><section class="tour-panel"><header><div><span>SHOWCASE TOUR</span><b>{{t('tour.title')}}</b></div><button @click="close">×</button></header><div class="tour-progress"><i v-for="(_,i) in steps" :key="i" :class="{active:i<=index}"/></div><main><div class="step-no mono">0{{index+1}} / 0{{steps.length}}</div><div class="step-icon">{{step.icon}}</div><h2>{{step.title}}</h2><p>{{step.desc}}</p><div class="step-preview"><span>{{step.label}}</span><b>{{step.value}}</b><small>{{step.note}}</small></div></main><footer><button class="skip" @click="close">{{t('tour.skip')}}</button><div><button v-if="index>0" @click="index--">{{t('common.previous')}}</button><button class="next" @click="next">{{index===steps.length-1?t('tour.finish'):t('common.next')}}</button></div></footer></section></div></Teleport></template>
<script setup lang="ts">
import { computed,onBeforeUnmount,onMounted,ref,watch } from 'vue';import { useI18n } from 'vue-i18n';import { useRouter } from 'vue-router'
const props=defineProps<{modelValue:boolean}>();const emit=defineEmits<{(e:'update:modelValue',value:boolean):void}>();const {t}=useI18n(),router=useRouter();const index=ref(0);const open=computed(()=>props.modelValue)
const steps=computed(()=>[{icon:'◎',title:t('tour.step1Title'),desc:t('tour.step1Desc'),label:t('tour.step1Label'),value:'T-102 · RUNNING',note:'18 / 24 STEPS'},{icon:'!',title:t('tour.step2Title'),desc:t('tour.step2Desc'),label:'POST /api/auth/login',value:'500 ERROR',note:'RESPONSE + LOG + SCHEMA'},{icon:'⌁',title:t('tour.step3Title'),desc:t('tour.step3Desc'),label:'TRACE-102',value:'8 NODES',note:'1 FAILED PATH'},{icon:'✓',title:t('tour.step4Title'),desc:t('tour.step4Desc'),label:t('tour.step4Label'),value:'MEDIUM RISK',note:'2 BUGS · 84% COVERAGE'}]);const step=computed(()=>steps.value[index.value])
watch(open,v=>{if(v)index.value=0});function close(){emit('update:modelValue',false);localStorage.setItem('tp-tour-seen','true')}async function next(){if(index.value<steps.value.length-1){index.value++;if(index.value===2)await router.push('/trace/102');if(index.value===3)await router.push('/reports')}else{close();await router.push('/workspace')}}function onKey(e:KeyboardEvent){if(e.key==='Escape'&&open.value)close()}onMounted(()=>window.addEventListener('keydown',onKey));onBeforeUnmount(()=>window.removeEventListener('keydown',onKey))
</script>
<style scoped>
.tour-layer{position:fixed;inset:0;z-index:3000}.tour-scrim{position:absolute;inset:0;width:100%;border:0;background:rgba(2,7,12,.68);backdrop-filter:blur(2px)}.tour-panel{position:absolute;right:24px;top:72px;width:360px;border:1px solid var(--border-active);border-radius:8px;background:var(--bg-surface);box-shadow:0 24px 70px rgba(0,0,0,.42);overflow:hidden}.tour-panel header{display:flex;justify-content:space-between;align-items:flex-start;padding:15px 16px;border-bottom:1px solid var(--border-subtle)}.tour-panel header>div{display:grid;gap:4px}.tour-panel header span{color:var(--primary);font:9px var(--font-mono);letter-spacing:.08em}.tour-panel header b{font-size:13px}.tour-panel header button{width:24px;height:24px;border:0;background:none;color:var(--text-muted);font-size:18px;cursor:pointer}.tour-progress{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;padding:10px 16px 0}.tour-progress i{height:2px;background:var(--border)}.tour-progress i.active{background:var(--primary)}.tour-panel main{padding:18px 16px 20px}.step-no{color:var(--text-muted);font-size:9px}.step-icon{display:grid;place-items:center;width:34px;height:34px;margin:20px 0 12px;border:1px solid var(--border-active);border-radius:6px;background:var(--bg-selected);color:var(--primary);font-size:16px}.tour-panel h2{font-size:18px}.tour-panel main>p{min-height:52px;margin-top:7px;color:var(--text-secondary);font-size:11px;line-height:1.65}.step-preview{display:grid;grid-template-columns:1fr auto;gap:5px;margin-top:16px;padding:11px;border-left:2px solid var(--primary);background:var(--bg-elevated)}.step-preview span{color:var(--text-muted);font:9px var(--font-mono)}.step-preview b{font:10px var(--font-mono)}.step-preview small{grid-column:1/-1;color:var(--text-muted);font:9px var(--font-mono)}.tour-panel footer{display:flex;justify-content:space-between;padding:12px 16px;border-top:1px solid var(--border-subtle)}.tour-panel footer div{display:flex;gap:7px}.tour-panel footer button{height:30px;padding:0 11px;border:1px solid var(--border);border-radius:5px;background:var(--bg-elevated);color:var(--text-secondary);font-size:10px;cursor:pointer}.tour-panel footer .skip{border-color:transparent;background:none;color:var(--text-muted)}.tour-panel footer .next{border-color:var(--primary);background:var(--primary);color:#071018;font-weight:600}@media(max-width:520px){.tour-panel{left:12px;right:12px;top:auto;bottom:12px;width:auto}}
</style>
