/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentActivity: typeof import('./components/agent/AgentActivity.vue')['default']
    AgentComposer: typeof import('./components/agent/AgentComposer.vue')['default']
    AgentPlan: typeof import('./components/agent/AgentPlan.vue')['default']
    CoverageBar: typeof import('./components/common/CoverageBar.vue')['default']
    DemoGuide: typeof import('./components/common/DemoGuide.vue')['default']
    ElButton: typeof import('element-plus/es/components/button/index.mjs')['ElButton']
    ElDialog: typeof import('element-plus/es/components/dialog/index.mjs')['ElDialog']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es/components/form/index.mjs')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index.mjs')['ElFormItem']
    ElIcon: typeof import('element-plus/es/components/icon/index.mjs')['ElIcon']
    ElInput: typeof import('element-plus/es/components/input/index.mjs')['ElInput']
    ElOption: typeof import('element-plus/es/components/select/index.mjs')['ElOption']
    ElSelect: typeof import('element-plus/es/components/select/index.mjs')['ElSelect']
    ElSlider: typeof import('element-plus/es/components/slider/index.mjs')['ElSlider']
    ElTag: typeof import('element-plus/es/components/tag/index.mjs')['ElTag']
    JsonViewer: typeof import('./components/common/JsonViewer.vue')['default']
    LanguageSwitcher: typeof import('./components/common/LanguageSwitcher.vue')['default']
    MethodBadge: typeof import('./components/common/MethodBadge.vue')['default']
    RiskBadge: typeof import('./components/common/RiskBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeverityBadge: typeof import('./components/common/SeverityBadge.vue')['default']
    StatusBadge: typeof import('./components/common/StatusBadge.vue')['default']
    ThemeSwitcher: typeof import('./components/common/ThemeSwitcher.vue')['default']
    ToolCallCard: typeof import('./components/common/ToolCallCard.vue')['default']
  }
}
